name: Python Workflow
on: [push]

jobs:
  lint:
    uses: gh-actions-workflows/python-workflows/.github/workflows/flake8.yaml@1.2
    with:
      python-version: '3.10'

  # test:
  #   needs: lint
  #   uses: gh-actions-workflows/python-workflows/.github/workflows/pytest.yaml@1.2
      # with:
      #   python-version: '3.10' 

  publish:
    uses: gh-actions-workflows/docker-workflows/.github/workflows/docker-publish.yaml@v1.0
    if: ${{ github.ref_name == 'master' || github.ref_name == 'develop'}}
    needs: lint
    with:
      app_name: "brain-agriculture-challenge"
      docker_hub_user: ${{ vars.DOCKER_HUB_USER }}
    secrets:
      docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  # deploy:
  #   if: ${{ github.ref_name == 'master' }}
  #   needs: publish
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to Render
  #       uses: gh-actions-workflows/deploy-docker-render@v1.3
  #       with:
  #         deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
  #         render-api-key: ${{ secrets.RENDER_API_KEY }}
  #         image-url: ${{ needs.publish.outputs.image_name }}
